<font color='green' size = 5>Homework #1 - ECEN 4005 - Sanjay Kumar Keshava</font>



In [64]:
import numpy as np
import qutip as qt
from qutip.qip.operations import x_gate, y_gate, z_gate, s_gate, t_gate
, snot, rx, ry, rz, swap ,iswap, swapalpha,cnot, cz_gate, globalphase

%matplotlib notebook
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


In [2]:
si = qt.qeye(2); sx = qt.sigmax(); sy = qt.sigmay(); sz = qt.sigmaz();


<font color='green' size = 5>Problem 1(a) - Hermitian Operators</font>

In [3]:
si

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [4]:
sx

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [5]:
sy

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [6]:
sz

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [7]:
si.dag()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [8]:
sx.dag()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [9]:
sy.dag()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [10]:
sz.dag()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [11]:
si.dag()-si

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]

In [12]:
sx.dag()-sx

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]

In [13]:
sy.dag()-sy

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]

In [14]:
sz.dag()-sz

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]




<font color='green' size = 5>Problem 1(a) - Unitary Operators</font>

In [15]:
si.dag()*si

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [16]:
sx.dag()*sx

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [17]:
sy.dag()*sy

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [18]:
sz.dag()*sz

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

<font color='green' size = 5>Problem 1(a) - Eigenvalues and Eigenvectors</font>

In [19]:
si.eigenstates()

(array([1., 1.]),
 array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[-1.]
         [ 0.]]                                                      ,
        Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[0.]
         [1.]]                                                       ],
       dtype=object))

In [20]:
sx.eigenstates()

(array([-1.,  1.]),
 array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[-0.70710678]
         [ 0.70710678]]                                              ,
        Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[0.70710678]
         [0.70710678]]                                               ],
       dtype=object))

In [21]:
sy.eigenstates()

(array([-1.,  1.]),
 array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[-0.70710678+0.j        ]
         [ 0.        +0.70710678j]]                                  ,
        Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[-0.70710678+0.j        ]
         [ 0.        -0.70710678j]]                                  ],
       dtype=object))

In [22]:
sz.eigenstates()

(array([-1.,  1.]),
 array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[ 0.]
         [-1.]]                                                      ,
        Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[-1.]
         [ 0.]]                                                      ],
       dtype=object))

<font color='green' size = 5>Problem 1(b) - Commutation Relations</font>

In [23]:
qt.commutator(sx, sy) 

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.+2.j 0.+0.j]
 [0.+0.j 0.-2.j]]

In [24]:
2*1j*sz

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.+2.j 0.+0.j]
 [0.+0.j 0.-2.j]]

In [25]:
qt.commutator(sy, sz) 

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.+0.j 0.+2.j]
 [0.+2.j 0.+0.j]]

In [26]:
2*1j*sx

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.+0.j 0.+2.j]
 [0.+2.j 0.+0.j]]

In [27]:
qt.commutator(sz, sx) 

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[ 0.  2.]
 [-2.  0.]]

In [28]:
2*1j*sy

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[ 0.  2.]
 [-2.  0.]]

<font color='green' size = 5>Problem 1(c) - Uncertainity Relation</font>

In [29]:
comm_sx_sy = 2*1j*sz; comm_sx_sy

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.+2.j 0.+0.j]
 [0.+0.j 0.-2.j]]

In [30]:
zero = qt.basis(2,0); zero

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [31]:
min_uncertainity = abs(((zero.dag()*comm_sx_sy*zero)/2)[0,0])

In [32]:
min_uncertainity

1.0

<font color='green' size = 5>Problem 4(a) - Equivalent Gates</font>

In [37]:
sx - snot()*sz*snot()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]

<font color='green' size = 5>Problem 4(b) - Equivalent Gates</font>

In [40]:
snot()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

In [42]:
rx(np.pi)*ry(np.pi/2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.-0.70710678j 0.-0.70710678j]
 [0.-0.70710678j 0.+0.70710678j]]

In [44]:
snot() - (1j)*rx(np.pi)*ry(np.pi/2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]

<font color='green' size = 5>Problem 4(c) - Equivalent Gates</font>

In [49]:
cnot() - qt.tensor(si, ry(np.pi/2))*cz_gate()*qt.tensor(si, ry(np.pi/(-2)))

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

<font color='green' size = 5>Problem 5(a) - SWAP and iSWAP</font>

In [76]:
plus = (qt.basis(2,0) + qt.basis(2,1)).unit(); minus = (qt.basis(2,0) - qt.basis(2,1)).unit(); 
plusminus = qt.tensor(plus,minus); plusminus

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.5]
 [-0.5]
 [ 0.5]
 [-0.5]]

In [66]:
swap()*plusminus

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.5]
 [ 0.5]
 [-0.5]
 [-0.5]]

In [67]:
qt.concurrence(swap()*plusminus)

0

In [68]:
iswap()*plusminus

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.5+0.j ]
 [ 0. +0.5j]
 [ 0. -0.5j]
 [-0.5+0.j ]]

In [69]:
qt.concurrence(iswap()*plusminus)

0.9999999864330515

<font color='green' size = 5>Problem 5(b) - SWAP and iSWAP</font>

In [73]:
onezero = qt.tensor(qt.basis(2,1),qt.basis(2,0)); onezero

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]

In [74]:
iswap()*onezero

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.+0.j]
 [0.+1.j]
 [0.+0.j]
 [0.+0.j]]

In [75]:
qt.concurrence(iswap()*onezero)

0